### ISSUE TITLE
Allow for discussions

### ISSUE THREAD

**Issue by trajano** [piratepartyca/piratepartyca.github.io#1]
Can you add a comment system?  I personally use Disqus on my blog because it is easy enough to integrate.  However there's also  http://ivanzuzak.info/2011/02/18/github-hosted-comments-for-github-hosted-blogs.html that shows hwo to integrate the GitHub issues system.

Good luck on 2018

**Comment by teamcoltra** [comment]
Hey @trajano thanks for the comment, I probably need to link to this repo directly in the site somewhere, I just don't want to make it overly cluttered... probably in the footer. 

Anyway, currently I am going to hold off on your suggestion. I purposely avoided using a commenting system because we would rather people have conversations on social media than on our site. Plus as per our new policy of ultra-minimal: we don't want to take on new projects that require any moderate to significant dedication of human bandwidth. I feel moderating conversations would fail that.

Finally there is an optics reason we would consider not having comments, largely on our old site no one had commented. This at least has the illusion that no one is reading our posts. 

I am marking this "closed" but you and others are welcome to discuss this further

**Comment by trajano** [comment]
I don't believe in moderating, short of preventing spam, but I would not allow anonymous commenting if I were to do it.  That's how www.trajano.net has been running for a while.  I also use Disqus which already has a facility to flag and deal with spammers.

I think it's better if Disqus is used just to provide the facility and we get Google/Facebook integration for free.  Disqus is also not filtered out by corporate filters as much as say ... Facebook.

Disqus allows us to export later https://help.disqus.com/customer/portal/articles/472149-comments-export

One thing you have to do though is add a link to their privacy policy, to give you an idea, here's how I did it on mine https://www.trajano.net/privacy-policy/

I used GA for analytics, Media.net for ads and Disqus for comments.

**Comment by trajano** [comment]
As for optics, I would say having to have another ID and network that is not associated with whatever we are already using is annoying to say the least and I would have to admit that it is more of a bother.

There are already many Disqus sites www.trajano.net included that you can leverage the social interactions already.  Facebook would be better, but you won't be able to export and you'd have firewall issues.

**Comment by trajano** [comment]
I created a PR that would demonstrate having a comment area.  However as you have stated we want it to be minimal and I cannot guarantee my effort, but at least you'd have a sample.  Let me know if you want to go with the Disqus approach, I will ask tech support to transfer ownership of the piratepartyca.disqus.com to your ID if you have one.

**Comment by teamcoltra** [comment]
I have still not been convinced that commenting is a good thing, I will add social share buttons and I even tried your pull to see how it looks and it looks nice... but for now we are going to pass.

**Comment by teamcoltra** [comment]
Internal discussions on our posts can happen by subscribing to our mailing lists and then emailing list@pirateparty.ca which will actually go out to many people and you can start a real conversation there.

**Comment by trajano** [comment]
That's actually a barrier, most people I know are already dealing with a deluge of messages in the e-mail the notion of adding oneself to a mailing list would be a barrier for them including myself.

No offence taken/intended, just letting you know a different side of the coin.

**Comment by teamcoltra** [comment]
Then we have other options like commenting on FB, etc. The world of commenting directly on articles is going away, Wired hides comments by default, ARSTechnica puts them elsewhere, Verge, Bustle, CNN, etc all have removed comments from their website. 

It's not that I don't hear your side of the argument, and I appreciate it. For now, it's just not something we want to move forward on. I really do appreciate your efforts on this. :) 

What languages do you know (programming)

**Comment by trajano** [comment]
Programming languages: almost anything under the sun, and if not I can learn it PDQ. ^_^

True regarding comments going away on some websites.  They are large enough that can just rely on links and do queries on each social network.  Usually they have sub-teams for each major social network to manage it.  I guess that being said having no comments is fine in a way, but we should have "share links" then.

**Comment by trajano** [comment]
BTW, here's one other reason why large media outlets would likely not use services like Disqus... https://www.trajano.net/2015/09/toronto-sun-comment-censorship/ as they will get caught censoring comments.
